---
title: "MP4 Women Directors"
author: "Ivette Viramontes, Annah Lee, & Guadalupe Chimil"
date: "5/8/2018"
output: html_document
---

<<<<<<< HEAD
```{r}
library(mdsr)
library(RMySQL)
library(tidyverse)
library(ggplot2)
db <- dbConnect_scidb(dbname = "imdb")
class(db)
db %>%
=======
```{r} 
library(mdsr)
library(RMySQL)
library(tidyverse) 
library(rvest)
library(ggplot2)

db <- dbConnect_scidb(dbname = "imdb")

class(db)

Women_Direct <- db %>%
>>>>>>> 8e31e70a71e03b683df8a5b75f7983e09ac015af
  dbGetQuery("SELECT name.id, name.name, name.gender, cast_info.movie_id, cast_info.role_id, movie_info.info_type_id, movie_info.info, aka_title.production_year
FROM name
JOIN cast_info ON cast_info.person_id = name.id 
JOIN movie_info ON movie_info.movie_id= cast_info.movie_id
JOIN aka_title ON aka_title.movie_id= cast_info.movie_id
WHERE name.gender= 'f'
AND role_id= '8'
AND movie_info.info_type_id= '3'
AND aka_title.production_year BETWEEN 2000 AND 2018;")
<<<<<<< HEAD
db %>%
  dbGetQuery(sql)
```

=======
head(Women_Direct) 

#db %>%
  #dbGetQuery(sql)

#women_plot <- ggplot

```
>>>>>>> 8e31e70a71e03b683df8a5b75f7983e09ac015af
